export const TOOL_COLORS: Record<string, string> = {
  Bash: 'text-tool-bash',
  Read: 'text-tool-read',
  Grep: 'text-tool-grep',
  Glob: 'text-tool-grep',
  Agent: 'text-tool-agent',
  SendMessage: 'text-tool-agent',
  Edit: 'text-tool-edit',
  Write: 'text-tool-write',
  NotebookEdit: 'text-tool-write',
  WebFetch: 'text-tool-read',
  WebSearch: 'text-tool-read',
  TodoWrite: 'text-tool-edit',
  AskUserQuestion: 'text-cyan-400',
  Skill: 'text-tool-agent',
}

export const TOOL_BG_COLORS: Record<string, string> = {
  Bash: 'bg-green-500/10 border-green-500/30',
  Read: 'bg-blue-500/10 border-blue-500/30',
  Grep: 'bg-yellow-500/10 border-yellow-500/30',
  Glob: 'bg-yellow-500/10 border-yellow-500/30',
  Agent: 'bg-purple-500/10 border-purple-500/30',
  SendMessage: 'bg-purple-500/10 border-purple-500/30',
  Edit: 'bg-orange-500/10 border-orange-500/30',
  Write: 'bg-cyan-500/10 border-cyan-500/30',
  NotebookEdit: 'bg-cyan-500/10 border-cyan-500/30',
  WebFetch: 'bg-blue-500/10 border-blue-500/30',
  WebSearch: 'bg-blue-500/10 border-blue-500/30',
  TodoWrite: 'bg-orange-500/10 border-orange-500/30',
  AskUserQuestion: 'bg-cyan-500/10 border-cyan-500/30',
  Skill: 'bg-purple-500/10 border-purple-500/30',
}

export const TOOL_ICONS: Record<string, string> = {
  Bash: '⚡',
  Read: '📄',
  Grep: '🔍',
  Glob: '📂',
  Agent: '🤖',
  SendMessage: '💬',
  Edit: '✏️',
  Write: '📝',
  NotebookEdit: '📓',
  WebFetch: '🌐',
  WebSearch: '🔎',
  TodoWrite: '📋',
  AskUserQuestion: '❓',
  Skill: '⚙️',
}
